<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-28T17:21:40 IST" name="CollegeTestSuite" finished-at="2025-10-28T17:21:41 IST" duration-ms="184">
    <groups>
    </groups>
    <test started-at="2025-10-28T17:21:40 IST" name="Admission" finished-at="2025-10-28T17:21:40 IST" duration-ms="84">
      <class name="Testng1.Program1">
        <test-method signature="AdmissionBrokernLinks()[pri:0, instance:Testng1.Program1@12468a38]" started-at="2025-10-28T17:21:40 IST" name="AdmissionBrokernLinks" finished-at="2025-10-28T17:21:40 IST" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdmissionBrokernLinks -->
        <test-method signature="AdmissionLogin1()[pri:0, instance:Testng1.Program1@12468a38]" started-at="2025-10-28T17:21:40 IST" name="AdmissionLogin1" finished-at="2025-10-28T17:21:40 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AdmissionLogin1 -->
      </class> <!-- Testng1.Program1 -->
    </test> <!-- Admission -->
    <test started-at="2025-10-28T17:21:41 IST" name="Placement" finished-at="2025-10-28T17:21:41 IST" duration-ms="8">
      <class name="Testng1.Program2">
        <test-method signature="PlacementBrokenLink()[pri:0, instance:Testng1.Program2@55141def]" started-at="2025-10-28T17:21:41 IST" name="PlacementBrokenLink" finished-at="2025-10-28T17:21:41 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PlacementBrokenLink -->
        <test-method signature="PlacementLogin()[pri:0, instance:Testng1.Program2@55141def]" started-at="2025-10-28T17:21:41 IST" name="PlacementLogin" finished-at="2025-10-28T17:21:41 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PlacementLogin -->
      </class> <!-- Testng1.Program2 -->
    </test> <!-- Placement -->
    <test started-at="2025-10-28T17:21:41 IST" name="Faculty" finished-at="2025-10-28T17:21:41 IST" duration-ms="18">
      <class name="Testng1.Program3">
        <test-method signature="FacultyBrokenLinks()[pri:0, instance:Testng1.Program3@76505305]" started-at="2025-10-28T17:21:41 IST" name="FacultyBrokenLinks" finished-at="2025-10-28T17:21:41 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [B] but found [A]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [B] but found [A]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Testng1.Program3.FacultyBrokenLinks(Program3.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacultyBrokenLinks -->
        <test-method signature="FacultyLogin()[pri:0, instance:Testng1.Program3@76505305]" started-at="2025-10-28T17:21:41 IST" name="FacultyLogin" finished-at="2025-10-28T17:21:41 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FacultyLogin -->
      </class> <!-- Testng1.Program3 -->
    </test> <!-- Faculty -->
  </suite> <!-- CollegeTestSuite -->
</testng-results>
